<?php

/**
 * @file
 * Display Suite Reeses configuration.
 */

function ds_reeses() {
  return array(
    'label' => t('Reeses'),
    'regions' => array(
      'full_width' => t('Full Width'),
    ),
    // Uncomment if you want to include a CSS file for this layout (reeses.css)
    'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (reeses.png)
    // 'image' => TRUE,
  );
}
